import { Column, CreateDateColumn, Entity, Index, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';
import { ErrandTrustTier, RiderCodStatus, RiderCodTier, RiderIdentifierStatus, RiderStatus, VehicleType } from '@ore/contracts';

@Entity({ schema: 'dispatch' })
@Index('UQ_dispatch_rider_identifier', ['riderIdentifier'], { unique: true })
@Index('UQ_dispatch_rider_city_year_sequence', ['cityCode', 'approvalYear', 'sequenceNumber'], { unique: true })
/**
 * Serves the dispatch pool query: filter to AVAILABLE, then bound by a lat/lng box. Status leads
 * because it is the most selective column — the vast majority of riders are not available at any
 * given moment.
 */
@Index('IDX_dispatch_rider_pool', ['status', 'lat', 'lng'])
export class Rider {
  /** Internal UUID used for auth, wallet, dispatch assignments, tracking and joins. */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  userId: string;

  @Column()
  name: string;

  @Column()
  phone: string;

  @Column({ type: 'varchar', default: VehicleType.MOTORBIKE })
  vehicle: VehicleType;

  @Column({ type: 'varchar', nullable: true })
  licensePlate: string | null;

  @Column({ type: 'varchar', default: RiderStatus.OFFLINE })
  status: RiderStatus;

  @Column({ type: 'float', nullable: true })
  lat: number | null;

  @Column({ type: 'float', nullable: true })
  lng: number | null;

  // ── doc §5 eligibility & scoring ───────────────────────────────────
  @Column({ type: 'boolean', default: false })
  verified: boolean; // admin approval completed (doc: only verified riders get orders)

  /** Public Rider ID: YDR-CC-YYYY-NNNN, generated by backend only at approval. */
  @Column({ type: 'varchar', nullable: true })
  riderIdentifier: string | null;

  /** Controlled Ore operating-location id used to derive the Rider ID city code. */
  @Column({ type: 'varchar', nullable: true })
  cityId: string | null;

  /** Legal delivery-partner profile used by tax/settlement. Rider status alone is never employment classification. */
  @Column({ type: 'varchar', nullable: true })
  deliveryPartnerId: string | null;

  @Column({ type: 'varchar', default: 'INDEPENDENT_DELIVERY_PARTNER' })
  deliveryPartnerType: 'INDEPENDENT_DELIVERY_PARTNER' | 'FLEET_DELIVERY_PARTNER';

  @Column({ type: 'varchar', nullable: true })
  fleetPartnerId: string | null;

  @Column({ type: 'varchar', default: 'INDEPENDENT_DELIVERY_PARTNER' })
  contractType: string;

  @Column({ type: 'varchar', default: 'PAYSTACK_TRANSFER' })
  settlementMethod: string;

  @Column({ type: 'varchar', default: 'UNKNOWN' })
  residentStatus: string;

  /** Immutable city code from the approved operating-location register. */
  @Column({ type: 'varchar', nullable: true })
  cityCode: string | null;

  @Column({ type: 'int', nullable: true })
  approvalYear: number | null;

  @Column({ type: 'int', nullable: true })
  sequenceNumber: number | null;

  @Column({ type: Date, nullable: true })
  approvedAt: Date | null;

  @Column({ type: 'varchar', default: RiderIdentifierStatus.UNASSIGNED })
  identifierStatus: RiderIdentifierStatus;

  @Column({ type: 'boolean', default: false })
  codBlocked: boolean; // cash-blocked due to unresolved COD issues — excluded from COD pool

  @Column({ type: 'varchar', nullable: true })
  codBlockReason: string | null; // 'admin' (manual) | 'limit' (90%-of-tier engine) — admin blocks never auto-clear

  // ── doc §5 COD control — tier/status owned here, engine (ledger) updates via events ──
  @Column({ type: 'varchar', default: RiderCodTier.NEW })
  codTier: RiderCodTier;

  @Column({ type: 'varchar', default: RiderCodStatus.CLEAR })
  codStatus: RiderCodStatus;

  @Column({ type: 'int', default: 0 })
  completedDeliveries: number;

  // ── doc §Errands trust tiers (NEW 300 / VERIFIED 1k / TRUSTED 3k / CAP 5k) ──
  @Column({ type: 'varchar', default: ErrandTrustTier.NEW })
  errandTrustTier: ErrandTrustTier;

  @Column({ type: 'int', default: 0 })
  completedErrands: number;

  @Column({ type: 'float', default: 5.0 })
  rating: number;

  @Column({ type: 'float', default: 1.0 })
  reliabilityScore: number; // completion/reliability history (1.0 = neutral)

  /**
   * Offers made to this rider. The denominator for acceptance rate.
   *
   * Without it, `declineCount` is an absolute count that only ever grows, so a rider with 500
   * deliveries and 20 declines scores identically to one with 20 deliveries and 20 declines —
   * and past the clamp every veteran looks the same, which is where the signal stops
   * discriminating at all.
   */
  @Column({ type: 'int', default: 0 })
  offerCount: number;

  @Column({ type: 'int', default: 0 })
  declineCount: number;

  @Column({ type: 'int', default: 0 })
  timeoutCount: number;

  @Column({ type: 'int', default: 0 })
  cancellationCount: number;

  @Column({ type: Date, nullable: true })
  restrictedUntil: Date | null;

  @Column({ type: 'varchar', nullable: true })
  restrictionReason: string | null;

  @Column({ type: Date, nullable: true })
  cooldownUntil: Date | null; // repeated declines/timeouts → temporary cooldown

  @Column({ type: Date, nullable: true })
  lastJobAt: Date | null;

  @Column({ type: Date, nullable: true })
  idleSince: Date | null;

  @Column({ type: Date, nullable: true })
  pausedUntil: Date | null;

  @Column({ type: Date, nullable: true })
  sessionEndsAt: Date | null;

  @Column({ type: 'int', default: 0 })
  maxCodLimitPesewas: number; // 0 = no COD eligibility cap (tiers applied in COD engine)

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
