/**
 * Baseline schema for the `ledger` service, generated from its entity definitions.
 *
 * Production runs with `synchronize: false`, so migrations are the only thing that builds a
 * database — but this service's chain began by altering tables that nothing had created. A
 * fresh deploy failed at boot. Dev and test never caught it because they use
 * `synchronize: true` and skip migrations entirely.
 *
 * Every statement is guarded, so this is a no-op against a database that already has the
 * objects: safe to apply to an existing deployment as well as a new one.
 */
import { MigrationInterface, QueryRunner } from 'typeorm';

export class BaselineLedger1750000000000 implements MigrationInterface {
  name = 'BaselineLedger1750000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const driver = queryRunner.connection.options.type;
    if (driver === 'better-sqlite3' || driver === 'sqlite' || driver === 'sqljs') return; // sqlite dev uses synchronize

    await queryRunner.query('CREATE SCHEMA IF NOT EXISTS "ledger"');
    await queryRunner.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');

    const statements: string[] = [
      "CREATE TABLE \"ledger\".\"ledger_entry\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"orderId\" character varying, \"account\" character varying NOT NULL, \"debitPesewas\" integer NOT NULL DEFAULT '0', \"creditPesewas\" integer NOT NULL DEFAULT '0', \"ref\" character varying, \"idempotencyKey\" character varying, \"metaJson\" text, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_04e9d274911f909a5848a15cd74\" PRIMARY KEY (\"id\"))",
      "CREATE INDEX \"IDX_ed7b720c49c7ad9177e748c303\" ON \"ledger\".\"ledger_entry\" (\"account\", \"createdAt\") ",
      "CREATE INDEX \"IDX_648635a12ec8f4f524c203f0ab\" ON \"ledger\".\"ledger_entry\" (\"orderId\") ",
      "CREATE TABLE \"ledger\".\"ledger_idempotency\" (\"id\" character varying NOT NULL, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_4c71628f3fa9672b03b00895aac\" PRIMARY KEY (\"id\"))",
      "CREATE TABLE \"ledger\".\"money_breakdown\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"orderId\" character varying NOT NULL, \"subtotalPesewas\" integer NOT NULL, \"deliveryFeePesewas\" integer NOT NULL, \"serviceFeePesewas\" integer NOT NULL, \"platformFeePesewas\" integer NOT NULL, \"vendorSharePesewas\" integer NOT NULL, \"riderFeePesewas\" integer NOT NULL, \"pspFeePesewas\" integer NOT NULL DEFAULT '0', \"totalPesewas\" integer NOT NULL, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_c4d3aa9ad81161f463b59013d16\" UNIQUE (\"orderId\"), CONSTRAINT \"PK_1b0e179918f9a2a4fe01028456d\" PRIMARY KEY (\"id\"))",
      "CREATE TABLE \"ledger\".\"cod_cash\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"orderId\" character varying NOT NULL, \"riderId\" character varying NOT NULL, \"amountPesewas\" integer NOT NULL, \"status\" character varying NOT NULL DEFAULT 'EXPECTED', \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_4278d289fe216d0d832dcc4e663\" UNIQUE (\"orderId\"), CONSTRAINT \"PK_6f020031c8494ea9ceaec12870c\" PRIMARY KEY (\"id\"))",
      "CREATE INDEX \"IDX_58d4a3fe05569d4815024093be\" ON \"ledger\".\"cod_cash\" (\"riderId\", \"status\") ",
      "CREATE TABLE \"ledger\".\"rider_balance\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"riderId\" character varying NOT NULL, \"userId\" character varying, \"pendingPesewas\" integer NOT NULL DEFAULT '0', \"clearedPesewas\" integer NOT NULL DEFAULT '0', \"lockedPesewas\" integer NOT NULL DEFAULT '0', \"cashOwedPesewas\" integer NOT NULL DEFAULT '0', \"feesEarnedPesewas\" integer NOT NULL DEFAULT '0', \"remittedPesewas\" integer NOT NULL DEFAULT '0', \"clearsAt\" TIMESTAMP, \"withdrawalDay\" character varying, \"withdrawnTodayPesewas\" integer NOT NULL DEFAULT '0', \"withdrawalsTodayCount\" integer NOT NULL DEFAULT '0', \"version\" integer NOT NULL, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_842a39314e1eae165527c517033\" UNIQUE (\"riderId\"), CONSTRAINT \"PK_e9d1a071109816dbd307d02936b\" PRIMARY KEY (\"id\"))",
      "CREATE TABLE \"ledger\".\"rider_withdrawal\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"riderId\" character varying NOT NULL, \"amountPesewas\" integer NOT NULL, \"feePesewas\" integer NOT NULL DEFAULT '0', \"destination\" character varying NOT NULL, \"status\" character varying NOT NULL DEFAULT 'REQUESTED', \"transferReference\" character varying, \"adminNote\" character varying, \"processedAt\" TIMESTAMP, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_5a4e884501a2298f96790261873\" PRIMARY KEY (\"id\"))",
      "CREATE INDEX \"IDX_3604f3a47972f0b06ba52a3557\" ON \"ledger\".\"rider_withdrawal\" (\"riderId\", \"status\") ",
      "CREATE TABLE \"ledger\".\"reconcile_run\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"period\" date NOT NULL, \"status\" character varying NOT NULL DEFAULT 'RUNNING', \"reportJson\" text, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_d39ce4ab4cea56ea6e15ebe3909\" PRIMARY KEY (\"id\"))",
      "CREATE TABLE \"ledger\".\"vendor_earning\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"vendorId\" character varying NOT NULL, \"orderId\" character varying NOT NULL, \"orderRef\" character varying, \"amountPesewas\" integer NOT NULL, \"settlementId\" character varying, \"settledAt\" TIMESTAMP, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_c462d883fe9ff314a40a9571b76\" UNIQUE (\"orderId\"), CONSTRAINT \"PK_7a206d6c4c6dca88593f538e2a8\" PRIMARY KEY (\"id\"))",
      "CREATE INDEX \"IDX_b52b58d21fd77b0d7705091b9f\" ON \"ledger\".\"vendor_earning\" (\"vendorId\", \"settledAt\") ",
      "CREATE TABLE \"ledger\".\"vendor_settlement\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"vendorId\" character varying NOT NULL, \"cycleStart\" TIMESTAMP NOT NULL, \"cycleEnd\" TIMESTAMP NOT NULL, \"grossPesewas\" integer NOT NULL DEFAULT '0', \"debtAppliedPesewas\" integer NOT NULL DEFAULT '0', \"reservePesewas\" integer NOT NULL DEFAULT '0', \"payoutPesewas\" integer NOT NULL DEFAULT '0', \"status\" character varying NOT NULL DEFAULT 'READY', \"transferReference\" character varying, \"note\" character varying, \"paidAt\" TIMESTAMP, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_f320cc95824c8131c4f42e343d0\" PRIMARY KEY (\"id\"))",
      "CREATE INDEX \"IDX_2ac4f6a2888bfe625fc6b8be38\" ON \"ledger\".\"vendor_settlement\" (\"vendorId\", \"cycleStart\") ",
      "CREATE TABLE \"ledger\".\"vendor_balance\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"vendorId\" character varying NOT NULL, \"accruedPesewas\" integer NOT NULL DEFAULT '0', \"reservePesewas\" integer NOT NULL DEFAULT '0', \"owedPesewas\" integer NOT NULL DEFAULT '0', \"withdrawalHeldPesewas\" integer NOT NULL DEFAULT '0', \"paidOutPesewas\" integer NOT NULL DEFAULT '0', \"bonusPesewas\" integer NOT NULL DEFAULT '0', \"version\" integer NOT NULL, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_9c920c0a7d71ce91cffa01e52ad\" UNIQUE (\"vendorId\"), CONSTRAINT \"PK_89839aa4662c51ce6db973d7f85\" PRIMARY KEY (\"id\"))",
      "CREATE TABLE \"ledger\".\"vendor_withdrawal\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"vendorId\" character varying NOT NULL, \"amountPesewas\" integer NOT NULL, \"destination\" character varying NOT NULL, \"status\" character varying NOT NULL DEFAULT 'REQUESTED', \"transferReference\" character varying, \"note\" text, \"processedAt\" TIMESTAMP, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_29794de1453da8466cefb388115\" PRIMARY KEY (\"id\"))",
      "CREATE INDEX \"IDX_1ec88996be904e566f6773370e\" ON \"ledger\".\"vendor_withdrawal\" (\"vendorId\", \"status\") ",
      "CREATE TABLE \"ledger\".\"dispute\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"orderId\" character varying NOT NULL, \"customerId\" character varying NOT NULL, \"vendorId\" character varying NOT NULL, \"reason\" character varying NOT NULL, \"description\" text NOT NULL, \"evidenceKeys\" text, \"status\" character varying NOT NULL DEFAULT 'OPEN', \"fault\" character varying, \"decisionPesewas\" integer NOT NULL DEFAULT '0', \"refundedPesewas\" integer NOT NULL DEFAULT '0', \"refundMethod\" character varying, \"note\" character varying, \"decidedBy\" character varying, \"decidedAt\" TIMESTAMP, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_b692f52ca0593aa85f1026ca220\" UNIQUE (\"orderId\"), CONSTRAINT \"PK_e2f1f4741f2094ce789b0a7c5b3\" PRIMARY KEY (\"id\"))",
      "CREATE INDEX \"IDX_2b41da7c7170448786d7c4d513\" ON \"ledger\".\"dispute\" (\"status\") ",
      "CREATE TABLE \"ledger\".\"chargeback\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"orderId\" character varying NOT NULL, \"reference\" character varying NOT NULL, \"amountPesewas\" integer NOT NULL, \"reason\" character varying NOT NULL, \"evidenceKeys\" text, \"status\" character varying NOT NULL DEFAULT 'OPEN', \"fault\" character varying, \"feesPesewas\" integer NOT NULL DEFAULT '0', \"refundedPesewas\" integer NOT NULL DEFAULT '0', \"note\" character varying, \"decidedBy\" character varying, \"decidedAt\" TIMESTAMP, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_e9dc8b5a04108b276565fb47972\" UNIQUE (\"orderId\"), CONSTRAINT \"UQ_6afe0e720521ecda0e113373c5b\" UNIQUE (\"reference\"), CONSTRAINT \"PK_b8733f1a59eed2643b7a879a915\" PRIMARY KEY (\"id\"))",
      "CREATE INDEX \"IDX_8cb14c9bee43b84f6d2f86698a\" ON \"ledger\".\"chargeback\" (\"status\") ",
      "CREATE TABLE \"ledger\".\"customer_credit\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"userId\" character varying NOT NULL, \"creditPesewas\" integer NOT NULL DEFAULT '0', \"lifetimeCreditedPesewas\" integer NOT NULL DEFAULT '0', \"lifetimeUsedPesewas\" integer NOT NULL DEFAULT '0', \"version\" integer NOT NULL, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_1e65b8f1a01f3d85eccbe9775b8\" UNIQUE (\"userId\"), CONSTRAINT \"PK_09d951d16d0900cbe0f2f3b17be\" PRIMARY KEY (\"id\"))",
      "CREATE TABLE \"ledger\".\"customer_credit_log\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"userId\" character varying NOT NULL, \"amountPesewas\" integer NOT NULL, \"ref\" character varying NOT NULL, \"kind\" character varying NOT NULL DEFAULT 'manual', \"expiresAt\" TIMESTAMP, \"expiredAt\" TIMESTAMP, \"reason\" character varying NOT NULL, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_2e325108a8622b18abb2aee047f\" UNIQUE (\"ref\"), CONSTRAINT \"PK_3e74ce25da9808659d4beed2b20\" PRIMARY KEY (\"id\"))",
      "CREATE TABLE \"ledger\".\"customer_loyalty\" (\"userId\" character varying NOT NULL, \"points\" integer NOT NULL DEFAULT '0', \"lifetimeEarned\" integer NOT NULL DEFAULT '0', \"lifetimeRedeemed\" integer NOT NULL DEFAULT '0', \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_89f17cd443bf88295a5aa1e6f9e\" PRIMARY KEY (\"userId\"))",
      "CREATE TABLE \"ledger\".\"chart_account\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"name\" character varying NOT NULL, \"code\" character varying NOT NULL, \"label\" character varying NOT NULL, \"nature\" character varying NOT NULL DEFAULT 'CONTROL', \"normalSide\" character varying NOT NULL DEFAULT 'DEBIT', \"mustNetToZero\" boolean NOT NULL DEFAULT false, \"note\" text, \"updatedBy\" character varying, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_3b6f6736efe7893ebc522b4524a\" PRIMARY KEY (\"id\"))",
      "CREATE UNIQUE INDEX \"IDX_f716fd7fc5a1272502c44ad3b5\" ON \"ledger\".\"chart_account\" (\"code\") ",
      "CREATE UNIQUE INDEX \"IDX_871510c3654ba210e0356eb0dd\" ON \"ledger\".\"chart_account\" (\"name\") ",
      "CREATE TABLE \"ledger\".\"accounting_period\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"year\" integer NOT NULL, \"month\" integer NOT NULL, \"label\" character varying NOT NULL, \"lockedBy\" character varying, \"reason\" character varying, \"trialBalanceJson\" text, \"netDebitPesewas\" integer NOT NULL DEFAULT '0', \"netCreditPesewas\" integer NOT NULL DEFAULT '0', \"balanced\" boolean NOT NULL DEFAULT false, \"lockedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_ef62d06c5d19f54b2b3cf6f8c81\" PRIMARY KEY (\"id\"))",
      "CREATE UNIQUE INDEX \"IDX_2188ec110f1baf6f0f636695d0\" ON \"ledger\".\"accounting_period\" (\"year\", \"month\") ",
      "CREATE TABLE \"ledger\".\"adjustment_request\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"ref\" character varying, \"status\" character varying NOT NULL DEFAULT 'PROPOSED', \"proposedBy\" character varying, \"decidedBy\" character varying, \"reason\" text NOT NULL, \"reversesRef\" character varying, \"orderId\" character varying, \"entriesJson\" text NOT NULL, \"amountPesewas\" integer NOT NULL DEFAULT '0', \"correctsPeriod\" character varying, \"executionRef\" character varying, \"executionNote\" character varying, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"decidedAt\" TIMESTAMP, \"executedAt\" TIMESTAMP, CONSTRAINT \"PK_fdaf73ac8f4bfda4db30b98f8bf\" PRIMARY KEY (\"id\"))",
      "CREATE UNIQUE INDEX \"IDX_739c273e2f320056661ae08b28\" ON \"ledger\".\"adjustment_request\" (\"executionRef\") ",
      "CREATE INDEX \"IDX_d72d4777d207e33d54489f9697\" ON \"ledger\".\"adjustment_request\" (\"status\", \"createdAt\") ",
      "CREATE TABLE \"ledger\".\"tax_rule\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"ruleId\" character varying NOT NULL, \"taxType\" character varying NOT NULL, \"supplierType\" character varying, \"payerType\" character varying, \"payeeType\" character varying, \"residentStatus\" character varying, \"transactionType\" character varying, \"contractType\" character varying, \"thresholdType\" character varying, \"thresholdAmountPesewas\" integer, \"rateBps\" integer NOT NULL, \"taxBase\" character varying NOT NULL DEFAULT 'TAXABLE_AMOUNT', \"effectiveFrom\" TIMESTAMP NOT NULL, \"effectiveTo\" TIMESTAMP, \"exemption\" boolean NOT NULL DEFAULT false, \"certificateRequired\" boolean NOT NULL DEFAULT false, \"active\" boolean NOT NULL DEFAULT true, \"version\" integer NOT NULL DEFAULT '1', \"updatedBy\" character varying, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_e04635f79e13b27615e2160d3e0\" PRIMARY KEY (\"id\"))",
      "CREATE UNIQUE INDEX \"IDX_0c3310693b5938c319eb295283\" ON \"ledger\".\"tax_rule\" (\"ruleId\") ",
      "CREATE INDEX \"IDX_080028e3e9600fc807837fb41d\" ON \"ledger\".\"tax_rule\" (\"taxType\", \"active\", \"effectiveFrom\") ",
      "CREATE TABLE \"ledger\".\"tax_transaction\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"transactionId\" character varying NOT NULL, \"orderId\" character varying, \"componentType\" character varying NOT NULL, \"payerType\" character varying, \"payerId\" character varying, \"payeeType\" character varying, \"payeeId\" character varying, \"supplierType\" character varying, \"supplierId\" character varying, \"customerId\" character varying, \"grossAmountPesewas\" integer NOT NULL, \"taxableAmountPesewas\" integer NOT NULL DEFAULT '0', \"taxCategory\" character varying, \"revenueOwner\" character varying, \"paymentProcessor\" character varying, \"settlementMethod\" character varying, \"contractType\" character varying, \"transactionType\" character varying, \"residentStatus\" character varying, \"classificationStatus\" character varying NOT NULL DEFAULT 'REVIEW_REQUIRED', \"whtStatus\" character varying NOT NULL DEFAULT 'REVIEW_REQUIRED', \"vatStatus\" character varying NOT NULL DEFAULT 'REVIEW_REQUIRED', \"reviewReason\" text, \"metadataJson\" text, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_50152fb959fda5f53d585998912\" PRIMARY KEY (\"id\"))",
      "CREATE INDEX \"IDX_70cbd4efded2fb8fe580563bad\" ON \"ledger\".\"tax_transaction\" (\"classificationStatus\", \"createdAt\") ",
      "CREATE INDEX \"IDX_87ea105751d9dee264e7327bde\" ON \"ledger\".\"tax_transaction\" (\"revenueOwner\") ",
      "CREATE INDEX \"IDX_b979318c38154a5c7fdac345d7\" ON \"ledger\".\"tax_transaction\" (\"orderId\") ",
      "CREATE INDEX \"IDX_4886d55c3f60dd8154f781616a\" ON \"ledger\".\"tax_transaction\" (\"transactionId\", \"componentType\") ",
      "CREATE TABLE \"ledger\".\"wht_decision\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"transactionId\" character varying NOT NULL, \"orderId\" character varying, \"componentType\" character varying NOT NULL, \"ruleId\" character varying, \"whtStatus\" character varying NOT NULL, \"supplierId\" character varying, \"supplierType\" character varying, \"payerType\" character varying, \"payeeType\" character varying, \"transactionType\" character varying, \"contractType\" character varying, \"residentStatus\" character varying, \"taxYear\" integer, \"currentTransactionAmountPesewas\" integer NOT NULL DEFAULT '0', \"priorCumulativeAmountPesewas\" integer NOT NULL DEFAULT '0', \"postTransactionCumulativeAmountPesewas\" integer NOT NULL DEFAULT '0', \"thresholdType\" character varying, \"thresholdAmountPesewas\" integer, \"thresholdReachedFlag\" boolean NOT NULL DEFAULT false, \"thresholdTriggerTransactionId\" character varying, \"rateBps\" integer NOT NULL DEFAULT '0', \"taxBasePesewas\" integer NOT NULL DEFAULT '0', \"whtAmountPesewas\" integer NOT NULL DEFAULT '0', \"certificateRequired\" boolean NOT NULL DEFAULT false, \"certificateNumber\" character varying, \"reviewReason\" character varying, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_080c58219f029f26d0572046b26\" PRIMARY KEY (\"id\"))",
      "CREATE INDEX \"IDX_76fc37a3b67a302f0db8536209\" ON \"ledger\".\"wht_decision\" (\"whtStatus\", \"createdAt\") ",
      "CREATE INDEX \"IDX_eb9d62b95c53850eeb6cf92970\" ON \"ledger\".\"wht_decision\" (\"supplierId\", \"taxYear\", \"transactionType\") ",
      "CREATE INDEX \"IDX_a61e60d7d26ece837b5aba06b8\" ON \"ledger\".\"wht_decision\" (\"transactionId\", \"componentType\") ",
      "CREATE TABLE \"ledger\".\"ore_tax_ledger\" (\"taxTransactionId\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"orderId\" character varying, \"invoiceId\" character varying, \"partyId\" character varying, \"taxType\" character varying NOT NULL, \"taxCategory\" character varying NOT NULL, \"taxableValuePesewas\" integer NOT NULL, \"taxRateBps\" integer NOT NULL, \"taxAmountPesewas\" integer NOT NULL, \"taxPeriod\" character varying NOT NULL, \"transactionDate\" TIMESTAMP NOT NULL, \"sourceTransaction\" character varying NOT NULL, \"sourceComponent\" character varying, \"ruleId\" character varying, \"reversalReference\" character varying, \"paymentStatus\" character varying NOT NULL DEFAULT 'CONFIRMED', \"filingStatus\" character varying NOT NULL DEFAULT 'OPEN', \"certificateNumber\" character varying, \"metaJson\" text, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_60c6da9354f90f154a4a946debb\" PRIMARY KEY (\"taxTransactionId\"))",
      "CREATE INDEX \"IDX_c97494cbff26df5232af2fde82\" ON \"ledger\".\"ore_tax_ledger\" (\"sourceTransaction\") ",
      "CREATE INDEX \"IDX_961219d61c6038052737e9fafa\" ON \"ledger\".\"ore_tax_ledger\" (\"taxType\", \"taxPeriod\") ",
      "CREATE INDEX \"IDX_36a7848875db989acdfd007396\" ON \"ledger\".\"ore_tax_ledger\" (\"partyId\") ",
      "CREATE INDEX \"IDX_9165803d005c5152b1787e078a\" ON \"ledger\".\"ore_tax_ledger\" (\"invoiceId\") ",
      "CREATE INDEX \"IDX_e6b31777699b627c97a7557d84\" ON \"ledger\".\"ore_tax_ledger\" (\"orderId\") ",
      "CREATE TABLE \"ledger\".\"tax_review_case\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"transactionId\" character varying NOT NULL, \"orderId\" character varying, \"componentType\" character varying, \"reasonCode\" character varying NOT NULL, \"reason\" text NOT NULL, \"status\" character varying NOT NULL DEFAULT 'OPEN', \"assignedTo\" character varying, \"resolvedBy\" character varying, \"resolvedAt\" TIMESTAMP, \"resolutionNote\" text, \"payloadJson\" text, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_2b24369338a4ca0672af9402534\" PRIMARY KEY (\"id\"))",
      "CREATE INDEX \"IDX_2d145d5895c76bbfcfc85c2b0d\" ON \"ledger\".\"tax_review_case\" (\"reasonCode\") ",
      "CREATE INDEX \"IDX_4cc5c065dce8aa6ea9c6c0ca93\" ON \"ledger\".\"tax_review_case\" (\"orderId\") ",
      "CREATE INDEX \"IDX_e9db55325bba114726c0968ae8\" ON \"ledger\".\"tax_review_case\" (\"status\", \"createdAt\") ",
    ];

    for (const sql of statements) {
      try {
        await queryRunner.query(sql);
      } catch (err) {
        // Already present (existing deployment) — the object this statement creates is exactly
        // what a later migration or an earlier deploy already produced. Anything else rethrows.
        const msg = (err as Error).message;
        if (!/already exists/i.test(msg)) throw err;
      }
    }
  }

  public async down(): Promise<void> {
    // Intentionally empty: dropping a service's entire schema is never what a rollback wants.
  }
}
